# Configurazione server TCP
serverTcpPort = 12345

# Parametri per la connessione al gruppo multicast
serverUdpPort = 12346
multicastAddress = 239.255.255.250

# porta d'ascolto e buffer del client per le notifiche udp
udpPort = 12347
udpReadBuffSize = 1024

# Dimensione del buffer per le operazioni di I/O (in byte)
writeBuffSize = 1024
readBuffSize = 2048

# Configurazione server RMI
serverHost = localhost
rmiPort = 1099
