# Porta TCP su cui il server ascolta le connessioni in ingresso 8080
port = 12345

# Numero di thread del thread pool per la gestione degli eventi I/O
threadPoolSize = 10

# Dimensione dei buffer per le operazioni di I/O (in byte)
readBufferSize = 1024
writeBufferSize = 2048

# Porta UDP per l'invio delle notifiche multicast
udpPort = 12346
# Indirizzo multicast utilizzato per le notifiche
multicastAddress = 239.255.255.250

# Timeout per logout automatico in secondi (20 min)
inactivityTimeout = 1200

# Porta per il servizio RMI
rmiPort = 1099